### ISSUE TITLE
Looks like a build error need help

### ISSUE THREAD

**Issue by sattishv** [uber/node-stap#26]
Hi Team,

Got this below error while trying to gather the trace .We have installed system tap, kernel headers etc 

[root@userstage7469 node-stap]# node cmd/torch.js 26743 raw 10 > raw.txt
module.js:327
    throw err;
    ^

Error: Cannot find module '../../../build/Release/demangle'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/x/ebay/cronus/software/service_nodes/.ENV202zz9301r.nodejstestweb-app__ENV202zz9301r.nodejstestweb-app__ENV202zz9301r-LVS03-CLilcvvesf-CPT203c72av4n/installed-packages/nodejstestweb/0.0.1_20161206164442588.unx/cronus/scripts/node_modules/node-stap/lib/elf-atos/loaders/elf_loader.js:29:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Thanks
Sattish.

**Comment by sattishv** [comment]
Hi team sorry to mention the node verison. Ours is 4.5.0

**Comment by Raynos** [comment]
We've only tested & supported this tool with node 0.10.32
